name: CD Workflow

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'feat/#2-ci-cd-pipeline'

permissions:
  contents: read

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}

  deploy-to-ec2:
    if: github.event_name == 'push'
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}"
            CONTAINER_NAME="idear-chain"

            sudo docker pull ${IMAGE_NAME}

            CONTAINER_ID=$(sudo docker ps -aqf "name=^/${CONTAINER_NAME}$")
            if [ -n "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            sudo docker run --name ${CONTAINER_NAME} -d \
                 -p 3000:3000 \
                 --restart unless-stopped \
                 -e NODE_ENV=production \
                 -e NETWORK=${{ secrets.NETWORK }} \
                 -e RPC_URL=${{ secrets.RPC_URL }} \
                 -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
                 ${IMAGE_NAME}

            sleep 10

            if ! sudo docker ps | grep -q ${CONTAINER_NAME}; then
              sudo docker logs ${CONTAINER_NAME}
              exit 1
            fi

            sudo docker system prune -f
